### ISSUE TITLE
Saving prefrences

### ISSUE THREAD

**Issue by Sajjadhosn** [x74353/Amphetamine#28]
Hi,

The more I search for the functionality of "Save Preferences", the less I find.

Is there any plans for implementing this functionality?

In the mean time, where does Amphetamine save its configurations, so I can backup and symlink it to my Dotfiles repository?

P.S. Works like a charm btw, I really appreciate the effort put into this application 👍

**Comment by Sajjadhosn** [comment]
I found a way around this but in no means I think it's an elegant one. You can export the Amphetamine defaults domain and later import it ( something I've done here for example https://github.com/Sajjadhosn/dotfiles/blob/master/macOS/defaults.sh#L30 ) to achieve this goal.

Backup:
`defaults export com.if.Amphetamine Amphetamine.plist`

Restore:
```
defaults delete com.if.Amphetamine
defaults import com.if.Amphetamine Amphetamine.plist
```

**Comment by x74353** [comment]
App preferences are cached in newer versions of macOS (maybe since 10.10?). Simply copying/replacing Amphetamine's .plist file will typically not work. You need to use the defaults tool as you mentioned in your previously comment. I currently do not have plans for implementing an "export prefs" feature. Time Machine backups should take care of most people's needs, and in your case, just make a copy of com.if.Amphetamine.plist. When you need to restore, use your delete and import defaults commands.

com.if.Amphetamine.plist is found here:
~/Library/Containers/com.if.Amphetamine/Data/Library/Preferences/com.if.Amphetamine.plist
